name: Build and push Docker image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get image tags
        id: get_tags
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
            echo "Detected version tag: $VERSION"
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            echo "tags=playermmcm/command-tasks:${VERSION},playermmcm/command-tasks:${MAJOR}.${MINOR},playermmcm/command-tasks:${MAJOR},playermmcm/command-tasks:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=playermmcm/command-tasks:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.get_tags.outputs.tags }}
